export interface ItemRecipe {
  id: string;
  nameEn: string;
  nameZh: string;
  rawId: string;
  enchantedId: string;
  superEnchantedId?: string;
  ratio1: number; // raw to enchanted
  ratio2?: number; // enchanted to super
  collection: string;
  collectionLevel: number;
  npcPrice?: number; // Price of enchanted item if sold to NPC
  superNpcPrice?: number; // Price of super enchanted item if sold to NPC
}

export const FLIP_ITEMS: ItemRecipe[] = [
  // --- FARMING ---
  {
    id: "WHEAT_BREAD",
    nameEn: "Wheat (Bread Path)",
    nameZh: "小麦 (面包路径)",
    rawId: "WHEAT",
    enchantedId: "ENCHANTED_BREAD",
    ratio1: 60,
    collection: "WHEAT",
    collectionLevel: 2,
    npcPrice: 60,
  },
  {
    id: "WHEAT_HAY",
    nameEn: "Wheat (Hay Bale Path)",
    nameZh: "小麦 (干草块路径)",
    rawId: "WHEAT",
    enchantedId: "ENCHANTED_WHEAT",
    superEnchantedId: "ENCHANTED_HAY_BALE",
    ratio1: 160,
    ratio2: 144,
    collection: "WHEAT",
    collectionLevel: 7,
    npcPrice: 160,
    superNpcPrice: 23040
  },
  {
    id: "SEEDS",
    nameEn: "Seeds",
    nameZh: "小麦种子",
    rawId: "SEEDS",
    enchantedId: "ENCHANTED_SEEDS",
    superEnchantedId: "BOX_OF_SEEDS",
    ratio1: 160,
    ratio2: 160,
    collection: "WHEAT",
    collectionLevel: 6,
    npcPrice: 80,
    superNpcPrice: 12800
  },
  {
    id: "MELON",
    nameEn: "Melon",
    nameZh: "西瓜",
    rawId: "MELON",
    enchantedId: "ENCHANTED_MELON_SLICE",
    superEnchantedId: "ENCHANTED_MELON",
    ratio1: 160,
    ratio2: 160,
    collection: "MELON",
    collectionLevel: 5,
    npcPrice: 80,
    superNpcPrice: 12800
  },
  {
    id: "CARROT",
    nameEn: "Carrot",
    nameZh: "胡萝卜",
    rawId: "CARROT_ITEM",
    enchantedId: "ENCHANTED_CARROT",
    superEnchantedId: "ENCHANTED_GOLDEN_CARROT",
    ratio1: 160,
    ratio2: 128,
    collection: "CARROT",
    collectionLevel: 5,
    npcPrice: 320,
    superNpcPrice: 40960
  },
  {
    id: "POTATO",
    nameEn: "Potato",
    nameZh: "土豆",
    rawId: "POTATO_ITEM",
    enchantedId: "ENCHANTED_POTATO",
    superEnchantedId: "ENCHANTED_BAKED_POTATO",
    ratio1: 160,
    ratio2: 160,
    collection: "POTATO",
    collectionLevel: 5,
    npcPrice: 320,
    superNpcPrice: 51200
  },
  {
    id: "PUMPKIN",
    nameEn: "Pumpkin",
    nameZh: "南瓜",
    rawId: "PUMPKIN",
    enchantedId: "ENCHANTED_PUMPKIN",
    superEnchantedId: "POLISHED_PUMPKIN",
    ratio1: 160,
    ratio2: 160,
    collection: "PUMPKIN",
    collectionLevel: 5,
    npcPrice: 640,
    superNpcPrice: 102400
  },
  {
    id: "SUGAR_CANE",
    nameEn: "Sugar Cane",
    nameZh: "甘蔗",
    rawId: "SUGAR_CANE",
    enchantedId: "ENCHANTED_SUGAR",
    superEnchantedId: "ENCHANTED_SUGAR_CANE",
    ratio1: 160,
    ratio2: 160,
    collection: "SUGAR_CANE",
    collectionLevel: 4,
    npcPrice: 320,
    superNpcPrice: 51200
  },
  {
    id: "NETHER_WART",
    nameEn: "Nether Wart",
    nameZh: "地狱庞",
    rawId: "NETHER_STALK",
    enchantedId: "ENCHANTED_NETHER_STALK",
    superEnchantedId: "ENCHANTED_NETHER_STALK_BLOCK",
    ratio1: 160,
    ratio2: 160,
    collection: "NETHER_WART",
    collectionLevel: 4,
    npcPrice: 640,
    superNpcPrice: 102400
  },
  {
    id: "COCOA",
    nameEn: "Cocoa Beans",
    nameZh: "可可豆",
    rawId: "COCOA_BEANS",
    enchantedId: "ENCHANTED_COCOA_BEANS",
    superEnchantedId: "ENCHANTED_COOKIE",
    ratio1: 160,
    ratio2: 128, // Wiki: 128 Enchanted Cocoa + 32 Enchanted Sugar
    collection: "COCOA_BEANS",
    collectionLevel: 4,
    npcPrice: 480,
    superNpcPrice: 76800
  },
  {
    id: "SNOW",
    nameEn: "Snowball",
    nameZh: "雪球",
    rawId: "SNOW_BALL",
    enchantedId: "ENCHANTED_SNOW_BLOCK",
    ratio1: 640, // Wiki: 4 stacks of 160
    collection: "SNOW_BALL",
    collectionLevel: 2,
    npcPrice: 600,
  },
  {
    id: "GLOWSTONE",
    nameEn: "Glowstone",
    nameZh: "萤石",
    rawId: "GLOWSTONE_DUST",
    enchantedId: "ENCHANTED_GLOWSTONE_DUST",
    superEnchantedId: "ENCHANTED_GLOWSTONE_BLOCK",
    ratio1: 160,
    ratio2: 192, // Wiki: 192 Enchanted Dust
    collection: "GLOWSTONE_DUST",
    collectionLevel: 4,
    npcPrice: 320,
    superNpcPrice: 61440
  },
  {
    id: "CLAY",
    nameEn: "Clay",
    nameZh: "粘土",
    rawId: "CLAY_BALL",
    enchantedId: "ENCHANTED_CLAY",
    ratio1: 160,
    collection: "CLAY_BALL",
    collectionLevel: 4,
    npcPrice: 480,
  },
  {
    id: "FLINT",
    nameEn: "Flint",
    nameZh: "燧石",
    rawId: "FLINT",
    enchantedId: "ENCHANTED_FLINT",
    ratio1: 160,
    collection: "GRAVEL",
    collectionLevel: 4,
    npcPrice: 640,
  },
  {
    id: "MUSHROOM_RED",
    nameEn: "Red Mushroom",
    nameZh: "红蘑菇",
    rawId: "RED_MUSHROOM",
    enchantedId: "ENCHANTED_RED_MUSHROOM",
    superEnchantedId: "ENCHANTED_HUGE_MUSHROOM_RED",
    ratio1: 160,
    ratio2: 160,
    collection: "MUSHROOM",
    collectionLevel: 5,
    npcPrice: 640,
    superNpcPrice: 102400
  },
  {
    id: "MUSHROOM_BROWN",
    nameEn: "Brown Mushroom",
    nameZh: "棕蘑菇",
    rawId: "BROWN_MUSHROOM",
    enchantedId: "ENCHANTED_BROWN_MUSHROOM",
    superEnchantedId: "ENCHANTED_HUGE_MUSHROOM_BROWN",
    ratio1: 160,
    ratio2: 160,
    collection: "MUSHROOM",
    collectionLevel: 5,
    npcPrice: 640,
    superNpcPrice: 102400
  },
  {
    id: "CACTUS",
    nameEn: "Cactus",
    nameZh: "仙人掌",
    rawId: "CACTUS",
    enchantedId: "ENCHANTED_CACTUS_GREEN",
    superEnchantedId: "ENCHANTED_CACTUS",
    ratio1: 160,
    ratio2: 160,
    collection: "CACTUS",
    collectionLevel: 5,
    npcPrice: 320,
    superNpcPrice: 51200
  },
  {
    id: "MUTTON",
    nameEn: "Mutton",
    nameZh: "生羊肉",
    rawId: "MUTTON",
    enchantedId: "ENCHANTED_MUTTON",
    superEnchantedId: "ENCHANTED_COOKED_MUTTON",
    ratio1: 160,
    ratio2: 160,
    collection: "MUTTON",
    collectionLevel: 4,
    npcPrice: 800,
    superNpcPrice: 128000
  },
  {
    id: "PORK",
    nameEn: "Pork",
    nameZh: "生猪肉",
    rawId: "PORK",
    enchantedId: "ENCHANTED_PORK",
    superEnchantedId: "ENCHANTED_COOKED_PORK",
    ratio1: 160,
    ratio2: 160,
    collection: "PORK",
    collectionLevel: 4,
    npcPrice: 800,
    superNpcPrice: 128000
  },
  {
    id: "RABBIT",
    nameEn: "Rabbit",
    nameZh: "生兔肉",
    rawId: "RABBIT",
    enchantedId: "ENCHANTED_RABBIT",
    superEnchantedId: "ENCHANTED_COOKED_RABBIT",
    ratio1: 160,
    ratio2: 160,
    collection: "RABBIT",
    collectionLevel: 4,
    npcPrice: 640,
    superNpcPrice: 102400
  },
  {
    id: "CHICKEN",
    nameEn: "Chicken",
    nameZh: "生鸡肉",
    rawId: "RAW_CHICKEN",
    enchantedId: "ENCHANTED_RAW_CHICKEN",
    superEnchantedId: "ENCHANTED_COOKED_CHICKEN",
    ratio1: 160,
    ratio2: 160,
    collection: "RAW_CHICKEN",
    collectionLevel: 4,
    npcPrice: 640,
    superNpcPrice: 102400
  },
  {
    id: "COW",
    nameEn: "Beef",
    nameZh: "生牛肉",
    rawId: "RAW_BEEF",
    enchantedId: "ENCHANTED_RAW_BEEF",
    superEnchantedId: "ENCHANTED_COOKED_BEEF",
    ratio1: 160,
    ratio2: 160,
    collection: "RAW_BEEF",
    collectionLevel: 4,
    npcPrice: 640,
    superNpcPrice: 102400
  },
  // --- FLOWERS ---
  {
    id: "DANDELION",
    nameEn: "Dandelion",
    nameZh: "蒲公英",
    rawId: "DANDELION",
    enchantedId: "ENCHANTED_DANDELION",
    ratio1: 160,
    collection: "FLOWER",
    collectionLevel: 2,
    npcPrice: 320,
  },
  {
    id: "POPPY",
    nameEn: "Poppy",
    nameZh: "虞美人",
    rawId: "POPPY",
    enchantedId: "ENCHANTED_POPPY",
    ratio1: 160,
    collection: "FLOWER",
    collectionLevel: 3,
    npcPrice: 320,
  },
  // --- MINING ---
  {
    id: "COBBLESTONE",
    nameEn: "Cobblestone",
    nameZh: "圆石",
    rawId: "COBBLESTONE",
    enchantedId: "ENCHANTED_COBBLESTONE",
    superEnchantedId: "ENCHANTED_COBBLESTONE_SUPER",
    ratio1: 160,
    ratio2: 160,
    collection: "COBBLESTONE",
    collectionLevel: 4,
    npcPrice: 160,
    superNpcPrice: 25600
  },
  {
    id: "COAL",
    nameEn: "Coal",
    nameZh: "煤炭",
    rawId: "COAL",
    enchantedId: "ENCHANTED_COAL",
    superEnchantedId: "ENCHANTED_COAL_BLOCK",
    ratio1: 160,
    ratio2: 160,
    collection: "COAL",
    collectionLevel: 4,
    npcPrice: 320,
    superNpcPrice: 51200
  },
  {
    id: "IRON",
    nameEn: "Iron",
    nameZh: "铁锭",
    rawId: "IRON_INGOT",
    enchantedId: "ENCHANTED_IRON",
    superEnchantedId: "ENCHANTED_IRON_BLOCK",
    ratio1: 160,
    ratio2: 160,
    collection: "IRON_INGOT",
    collectionLevel: 4,
    npcPrice: 480,
    superNpcPrice: 76800
  },
  {
    id: "GOLD",
    nameEn: "Gold",
    nameZh: "金锭",
    rawId: "GOLD_INGOT",
    enchantedId: "ENCHANTED_GOLD",
    superEnchantedId: "ENCHANTED_GOLD_BLOCK",
    ratio1: 160,
    ratio2: 160,
    collection: "GOLD_INGOT",
    collectionLevel: 4,
    npcPrice: 640,
    superNpcPrice: 102400
  },
  {
    id: "DIAMOND",
    nameEn: "Diamond",
    nameZh: "钻石",
    rawId: "DIAMOND",
    enchantedId: "ENCHANTED_DIAMOND",
    superEnchantedId: "ENCHANTED_DIAMOND_BLOCK",
    ratio1: 160,
    ratio2: 160,
    collection: "DIAMOND",
    collectionLevel: 4,
    npcPrice: 1280,
    superNpcPrice: 204800
  },
  {
    id: "EMERALD",
    nameEn: "Emerald",
    nameZh: "绿宝石",
    rawId: "EMERALD",
    enchantedId: "ENCHANTED_EMERALD",
    superEnchantedId: "ENCHANTED_EMERALD_BLOCK",
    ratio1: 160,
    ratio2: 160,
    collection: "EMERALD",
    collectionLevel: 4,
    npcPrice: 960,
    superNpcPrice: 153600
  },
  {
    id: "LAPIS",
    nameEn: "Lapis",
    nameZh: "青金石",
    rawId: "INK_SACK:4",
    enchantedId: "ENCHANTED_LAPIS_LAZULI",
    superEnchantedId: "ENCHANTED_LAPIS_LAZULI_BLOCK",
    ratio1: 160,
    ratio2: 160,
    collection: "LAPIS_LAZULI",
    collectionLevel: 4,
    npcPrice: 160,
    superNpcPrice: 25600
  },
  {
    id: "REDSTONE",
    nameEn: "Redstone",
    nameZh: "红石",
    rawId: "REDSTONE",
    enchantedId: "ENCHANTED_REDSTONE",
    superEnchantedId: "ENCHANTED_REDSTONE_BLOCK",
    ratio1: 160,
    ratio2: 160,
    collection: "REDSTONE",
    collectionLevel: 4,
    npcPrice: 160,
    superNpcPrice: 25600
  },
  {
    id: "SAND",
    nameEn: "Sand",
    nameZh: "沙子",
    rawId: "SAND",
    enchantedId: "ENCHANTED_SAND",
    ratio1: 160,
    collection: "SAND",
    collectionLevel: 4,
    npcPrice: 320,
  },
  {
    id: "ICE",
    nameEn: "Ice",
    nameZh: "冰",
    rawId: "ICE",
    enchantedId: "ENCHANTED_ICE",
    superEnchantedId: "ENCHANTED_PACKED_ICE",
    ratio1: 160,
    ratio2: 160,
    collection: "ICE",
    collectionLevel: 4,
    npcPrice: 160,
    superNpcPrice: 25600
  },
  // --- WOOD ---
  {
    id: "OAK",
    nameEn: "Oak Wood",
    nameZh: "橡木",
    rawId: "OAK_LOG",
    enchantedId: "ENCHANTED_OAK_LOG",
    ratio1: 160,
    collection: "OAK_LOG",
    collectionLevel: 4,
    npcPrice: 320,
  },
  {
    id: "SPRUCE",
    nameEn: "Spruce Wood",
    nameZh: "云杉木",
    rawId: "SPRUCE_LOG",
    enchantedId: "ENCHANTED_SPRUCE_LOG",
    ratio1: 160,
    collection: "SPRUCE_LOG",
    collectionLevel: 4,
    npcPrice: 320,
  },
  {
    id: "BIRCH",
    nameEn: "Birch Wood",
    nameZh: "白桦木",
    rawId: "BIRCH_LOG",
    enchantedId: "ENCHANTED_BIRCH_LOG",
    ratio1: 160,
    collection: "BIRCH_LOG",
    collectionLevel: 4,
    npcPrice: 320,
  },
  {
    id: "DARK_OAK",
    nameEn: "Dark Oak Wood",
    nameZh: "深色橡木",
    rawId: "DARK_OAK_LOG",
    enchantedId: "ENCHANTED_DARK_OAK_LOG",
    ratio1: 160,
    collection: "DARK_OAK_LOG",
    collectionLevel: 4,
    npcPrice: 320,
  },
  {
    id: "ACACIA",
    nameEn: "Acacia Wood",
    nameZh: "金合欢木",
    rawId: "ACACIA_LOG",
    enchantedId: "ENCHANTED_ACACIA_LOG",
    ratio1: 160,
    collection: "ACACIA_LOG",
    collectionLevel: 4,
    npcPrice: 320,
  },
  {
    id: "JUNGLE",
    nameEn: "Jungle Wood",
    nameZh: "丛林木",
    rawId: "JUNGLE_LOG",
    enchantedId: "ENCHANTED_JUNGLE_LOG",
    ratio1: 160,
    collection: "JUNGLE_LOG",
    collectionLevel: 4,
    npcPrice: 320,
  },
  // --- COMBAT ---
  {
    id: "ROTTEN_FLESH",
    nameEn: "Rotten Flesh",
    nameZh: "腐肉",
    rawId: "ROTTEN_FLESH",
    enchantedId: "ENCHANTED_ROTTEN_FLESH",
    superEnchantedId: "ENCHANTED_ROTTEN_FLESH_BLOCK",
    ratio1: 160,
    ratio2: 160,
    collection: "ROTTEN_FLESH",
    collectionLevel: 4,
    npcPrice: 640,
    superNpcPrice: 102400
  },
  {
    id: "BONE",
    nameEn: "Bone",
    nameZh: "骨头",
    rawId: "BONE",
    enchantedId: "ENCHANTED_BONE",
    superEnchantedId: "ENCHANTED_BONE_BLOCK",
    ratio1: 160,
    ratio2: 160,
    collection: "BONE",
    collectionLevel: 4,
    npcPrice: 640,
    superNpcPrice: 102400
  },
  {
    id: "STRING",
    nameEn: "String",
    nameZh: "线",
    rawId: "STRING",
    enchantedId: "ENCHANTED_STRING",
    ratio1: 160,
    collection: "STRING",
    collectionLevel: 4,
    npcPrice: 480,
  },
  {
    id: "SPIDER_EYE",
    nameEn: "Spider Eye",
    nameZh: "蜘蛛眼",
    rawId: "SPIDER_EYE",
    enchantedId: "ENCHANTED_SPIDER_EYE",
    ratio1: 160,
    collection: "SPIDER_EYE",
    collectionLevel: 4,
    npcPrice: 480,
  },
  {
    id: "GUNPOWDER",
    nameEn: "Gunpowder",
    nameZh: "火药",
    rawId: "GUNPOWDER",
    enchantedId: "ENCHANTED_GUNPOWDER",
    ratio1: 160,
    collection: "GUNPOWDER",
    collectionLevel: 4,
    npcPrice: 640,
  },
  {
    id: "ENDER_PEARL",
    nameEn: "Ender Pearl",
    nameZh: "末影珍珠",
    rawId: "ENDER_PEARL",
    enchantedId: "ENCHANTED_ENDER_PEARL",
    superEnchantedId: "ABSOLUTE_ENDER_PEARL",
    ratio1: 16,
    ratio2: 80,
    collection: "ENDER_PEARL",
    collectionLevel: 4,
    npcPrice: 80,
    superNpcPrice: 6400
  },
  {
    id: "SLIME",
    nameEn: "Slime Ball",
    nameZh: "粘液球",
    rawId: "SLIME_BALL",
    enchantedId: "ENCHANTED_SLIME_BALL",
    superEnchantedId: "ENCHANTED_SLIME_BLOCK",
    ratio1: 160,
    ratio2: 160,
    collection: "SLIME_BALL",
    collectionLevel: 4,
    npcPrice: 800,
    superNpcPrice: 128000
  },
  {
    id: "MAGMA_CREAM",
    nameEn: "Magma Cream",
    nameZh: "岩浆膏",
    rawId: "MAGMA_CREAM",
    enchantedId: "ENCHANTED_MAGMA_CREAM",
    ratio1: 160,
    collection: "MAGMA_CREAM",
    collectionLevel: 4,
    npcPrice: 1280,
  },
  // --- FISHING ---
  {
    id: "FISH",
    nameEn: "Raw Fish",
    nameZh: "生鱼",
    rawId: "RAW_FISH",
    enchantedId: "ENCHANTED_RAW_FISH",
    superEnchantedId: "ENCHANTED_COOKED_FISH",
    ratio1: 160,
    ratio2: 160,
    collection: "RAW_FISH",
    collectionLevel: 4,
    npcPrice: 960,
    superNpcPrice: 153600
  },
  {
    id: "SALMON",
    nameEn: "Raw Salmon",
    nameZh: "生鲑鱼",
    rawId: "RAW_FISH:1",
    enchantedId: "ENCHANTED_RAW_SALMON",
    superEnchantedId: "ENCHANTED_COOKED_SALMON",
    ratio1: 160,
    ratio2: 160,
    collection: "RAW_FISH",
    collectionLevel: 5,
    npcPrice: 1440,
    superNpcPrice: 230400
  }
];

export const ROMAN_NUMERALS: Record<number, string> = {
  1: "I", 2: "II", 3: "III", 4: "IV", 5: "V", 6: "VI", 7: "VII", 8: "VIII", 9: "IX", 10: "X"
};
